"use client";

import { useMemo, useState, type InputHTMLAttributes, type ReactNode } from "react";
import { Bell, Bot, Building2, FileClock, History, LayoutDashboard, Link2, Play, Search, Settings, ShieldCheck, Users } from "lucide-react";

const sources = [
  ["Ministerstvo hospodárstva SR", "MH SR", "https://www.mhsr.sk", "Ministerstvo", "6 h", "Discovery + HTML"],
  ["Eurofondy / Program Slovensko", "MIRRI SR", "https://www.eurofondy.gov.sk", "Eurofondy", "3 h", "Discovery + PDF"],
  ["Environmentálny fond", "Envirofond", "https://www.envirofond.sk", "Štátna organizácia", "12 h", "Discovery + Playwright"],
  ["Pôdohospodárska platobná agentúra", "PPA", "https://www.apa.sk", "Agrosektor", "6 h", "Discovery + dokumenty"],
  ["SIEA", "SIEA", "https://www.siea.sk", "Energetika a inovácie", "6 h", "HTML + PDF"],
  ["Plán obnovy SR", "Úrad vlády SR", "https://www.planobnovy.sk", "Plán obnovy", "4 h", "Discovery + HTML"],
  ["egrant", "egrant.sk", "https://www.egrant.sk", "Agregátor", "12 h", "Discovery + agregácia"],
  ["EU Funding & Tenders Portal", "Európska komisia", "https://ec.europa.eu/info/funding-tenders", "EÚ programy", "6 h", "Discovery + API"],
  ["ITMS21+", "MIRRI SR", "https://www.itms21.sk", "Technická infraštruktúra", "24 h", "Systémový portál"]
] as const;

const grants = [
  { id: "PSK-MH-2026-41", title: "Podpora energetickej efektívnosti podnikov", issuer: "MH SR", program: "Program Slovensko", status: "Otvorená", currentState: "Aktuálna", daysLeft: 44, deadline: "30.07.2026", allocation: "42 000 000 EUR", support: "50 000 - 2 000 000 EUR", cofinancing: "45 %", eligibleApplicants: "MSP a veľké podniky s projektom energetickej efektívnosti", matchClient: "GreenTech Solutions s.r.o.", match: 86, source: "Eurofondy / Program Slovensko" },
  { id: "MIRRI-DIGI-2026-08", title: "Digitalizácia služieb obcí a miest", issuer: "MIRRI SR", program: "Plán obnovy", status: "Zmenená", currentState: "Uzávierka čoskoro", daysLeft: 26, deadline: "12.07.2026", allocation: "18 000 000 EUR", support: "20 000 - 750 000 EUR", cofinancing: "10 %", eligibleApplicants: "Obce, mestá, VÚC a nimi zriadené organizácie", matchClient: "Mesto Liptovský Hrádok", match: 94, source: "Plán obnovy SR" },
  { id: "FPU-7-2026", title: "Tvorba javiskového diela a šírenie hudby", issuer: "FPU", program: "FPU 2026", status: "Ukončená", currentState: "Ukončená", daysLeft: -22, deadline: "25.05.2026", allocation: "podľa podprogramu", support: "individuálne", cofinancing: "podľa schémy", eligibleApplicants: "Kultúrne organizácie, umelci a verejné kultúrne inštitúcie", matchClient: "Kultúrne centrum Demo", match: 41, source: "Fond na podporu umenia" }
] as const;

const roles = { Admin: "Plný prístup ku zdrojom, AI, používateľom a audit logu", Pracovník: "Správa výziev, klientov, párovania a notifikácií", Klient: "Vlastné výzvy, zhody, prílohy a notifikácie" };
const nav = [["dashboard", "Dashboard", LayoutDashboard], ["sources", "Zdroje", Link2], ["grants", "Výzvy", FileClock], ["history", "História", History], ["ai", "AI analýza", Bot], ["clients", "Klienti", Building2], ["matching", "Párovanie", Users], ["notifications", "Notifikácie", Bell], ["admin", "Admin", Settings]] as const;

type Role = keyof typeof roles;
type Session = { name: string; email: string; role: Role; status?: string };
type Grant = typeof grants[number];
type CheckResult = { stamp: string; checked: number; changes: number; docs: number };

export default function Home() {
  const [session, setSession] = useState<Session | null>(null);
  const [active, setActive] = useState("dashboard");
  const [grantId, setGrantId] = useState(grants[0].id);
  const [check, setCheck] = useState<CheckResult | null>(null);
  const grant = useMemo(() => grants.find((item) => item.id === grantId) ?? grants[0], [grantId]);
  const title = nav.find(([id]) => id === active)?.[1] ?? "Dashboard";
  const runCheck = () => { setCheck({ stamp: new Date().toLocaleString("sk-SK"), checked: 34, changes: 3, docs: 2 }); setActive("dashboard"); };

  if (!session) return <AuthScreen onEnter={setSession} />;

  return <main className="min-h-screen bg-white text-slate-900">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-[1480px] flex-col gap-4 px-3 py-4 sm:px-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-[#18365f] text-white sm:h-12 sm:w-12"><ShieldCheck /></div><div><h1 className="m-0 text-xl font-semibold sm:text-2xl">Grant Monitor AI</h1><p className="m-0 text-xs text-slate-500 sm:text-sm">Bezpečné monitorovanie výziev, klientov a notifikácií</p></div></div><div className="grid gap-2 sm:flex sm:flex-wrap sm:items-center"><div className="flex items-center gap-2"><Badge tone={session.status ? "amber" : "green"}>{session.role}</Badge><span className="text-sm text-slate-600">{session.name}</span></div><div className="grid grid-cols-2 gap-2 sm:flex"><button onClick={() => setSession(null)} className="min-h-11 rounded-md border px-3 text-sm font-semibold">Odhlásiť</button><button onClick={runCheck} className="min-h-11 rounded-md bg-[#2f7a58] px-4 font-semibold text-white"><Play className="mr-2 inline h-4 w-4" />Kontrola</button></div></div></div></header>
    <div className="mx-auto grid max-w-[1480px] lg:grid-cols-[280px_1fr]"><aside className="border-b bg-slate-50 p-3 lg:border-b-0 lg:border-r lg:p-5"><Card className="mb-3 hidden p-4 lg:block"><p className="text-xs font-bold uppercase text-[#2f7a58]">Aktívny prístup</p><b>{session.role}</b><p className="text-sm text-slate-500">{session.status ?? roles[session.role]}</p></Card><nav className="flex gap-2 overflow-x-auto pb-1 lg:grid lg:overflow-visible">{nav.filter(([id]) => session.role === "Klient" ? !["sources", "admin"].includes(id) : true).map(([id, label, Icon]) => <button key={id} onClick={() => setActive(id)} className={`flex min-h-11 min-w-max items-center gap-2 rounded-md px-3 text-left text-sm font-semibold lg:w-full ${active === id ? "bg-[#18365f] text-white" : "text-slate-700 hover:bg-white"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav></aside><section className="min-w-0 p-3 sm:p-5"><div className="mb-5 grid gap-3 lg:flex lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-[#2f7a58]">Pracovný modul</p><h2 className="m-0 text-2xl font-semibold sm:text-3xl">{title}</h2></div><div className="relative w-full lg:w-auto"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400" /><input className="min-h-11 w-full rounded-md border px-9 lg:w-80" placeholder="Hľadať zdroj, výzvu, klienta..." /></div></div><LinkedGrant grant={grant} setActive={setActive} />{active === "dashboard" && <Dashboard check={check} />}{active === "sources" && <Sources />}{active === "grants" && <Grants grantId={grantId} setGrantId={setGrantId} setActive={setActive} />}{active === "history" && <HistoryPanel grant={grant} check={check} />}{active === "ai" && <AiPanel grant={grant} />}{active === "clients" && <Clients session={session} />}{active === "matching" && <Matching grant={grant} />}{active === "notifications" && <Notifications grant={grant} />}{active === "admin" && <Admin />}</section></div>
  </main>;
}

function AuthScreen({ onEnter }: { onEnter: (session: Session) => void }) {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [role, setRole] = useState<Role>("Admin");
  const [company, setCompany] = useState("GreenTech Solutions s.r.o.");
  const [email, setEmail] = useState("kontakt@firma.sk");
  const [demoReady, setDemoReady] = useState(false);
  const register = () => {
    setDemoReady(true);
    setTimeout(() => onEnter({ name: company || "Nový klient", email, role: "Klient", status: "Demo verzia klienta - čaká na plnú aktiváciu." }), 450);
  };

  return <main className="grid min-h-screen place-items-start bg-slate-100 p-3 text-slate-900 sm:place-items-center sm:p-6"><section className="grid w-full max-w-5xl overflow-hidden rounded-xl border bg-white shadow-xl lg:grid-cols-[.95fr_1.05fr]"><div className="bg-[#18365f] p-5 text-white sm:p-8"><ShieldCheck /><h1 className="mt-5 text-3xl font-semibold sm:text-4xl">Grant Monitor AI</h1><p>Vstupná brána pre admina, pracovníkov a klientov.</p><p>Novému klientovi stačí e-mail a názov spoločnosti. Demo verzia sa otvorí hneď, plnú aktiváciu následne potvrdí admin.</p><p>RBAC · audit log · schvaľovanie klientov · oddelené rozhrania</p></div><div className="p-5 sm:p-8"><div className="mb-5 grid gap-2 sm:flex"><button onClick={() => setMode("login")} className={`min-h-11 rounded-md border px-4 font-semibold ${mode === "login" ? "bg-[#18365f] text-white" : "bg-white"}`}>Prihlásenie</button><button onClick={() => setMode("register")} className={`min-h-11 rounded-md border px-4 font-semibold ${mode === "register" ? "bg-[#18365f] text-white" : "bg-white"}`}>Registrácia klienta</button></div>{mode === "login" ? <div className="grid gap-3"><Field label="E-mail" defaultValue="admin@grantmonitor.sk" /><Field label="Heslo" type="password" defaultValue="demo-demo" /><label className="grid gap-1 text-sm font-semibold text-slate-600">Rola<select value={role} onChange={(event) => setRole(event.target.value as Role)} className="min-h-11 rounded-md border px-3 text-slate-900"><option>Admin</option><option>Pracovník</option><option>Klient</option></select></label><button onClick={() => onEnter({ name: role === "Klient" ? "Klient Demo" : "Lukáš Lejko", email: "admin@grantmonitor.sk", role })} className="min-h-11 rounded-md bg-[#2f7a58] px-4 font-semibold text-white">Prihlásiť sa</button></div> : <div className="grid gap-3"><Field label="E-mail" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="meno@firma.sk" /><Field label="Názov spoločnosti" value={company} onChange={(event) => setCompany(event.target.value)} placeholder="Napr. GreenTech s.r.o." /><button onClick={register} className="min-h-11 rounded-md bg-[#2f7a58] px-4 font-semibold text-white">Získať demo verziu</button>{demoReady && <div className="rounded-lg border border-[#b8d8c8] bg-[#f7fbf9] p-4"><b>Demo verzia je pripravená.</b><p className="m-0 mt-1 text-sm text-slate-600">Klient si hneď pozrie ukážku výziev, zhôd a notifikácií. Admin neskôr doplní plný profil, oprávnenia a aktiváciu účtu.</p></div>}<p className="text-sm text-slate-500">Detailné údaje ako IČO, región, SK NACE a de minimis sa doplnia až v klientskom profile alebo pri plnej aktivácii.</p></div>}</div></section></main>;
}

function Field({ label, ...props }: { label: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="grid gap-1 text-sm font-semibold text-slate-600">{label}<input {...props} className="min-h-11 rounded-md border px-3 text-slate-900" /></label>; }
function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`rounded-lg border bg-white shadow-sm ${className}`}>{children}</div>; }
function Badge({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "blue" | "amber" | "red" }) { const c = { green: "bg-green-50 text-green-800", blue: "bg-blue-50 text-blue-800", amber: "bg-amber-50 text-amber-800", red: "bg-red-50 text-red-800" }[tone]; return <span className={`inline-flex min-h-7 items-center rounded-md px-2 text-xs font-bold ${c}`}>{children}</span>; }
function grantTone(g: Grant) { return g.daysLeft < 0 ? "red" : g.daysLeft < 30 ? "amber" : "green"; }
function LinkedGrant({ grant, setActive }: { grant: Grant; setActive: (id: string) => void }) { return <Card className="mb-5 border-[#b8d8c8] bg-[#f7fbf9] p-3 sm:p-4"><div className="grid gap-3 lg:flex lg:items-center lg:justify-between"><div className="min-w-0"><p className="text-xs font-bold uppercase text-[#2f7a58]">Prepojený záznam výzvy</p><h3 className="m-0 text-base font-semibold">{grant.title}</h3><p className="m-0 text-sm text-slate-600">{grant.id} · {grant.issuer} · uzávierka {grant.deadline}</p></div><div className="flex gap-2 overflow-x-auto pb-1">{[["grants","Detail"],["history","Zmeny"],["ai","AI"],["matching","Zhody"],["notifications","Notifikácie"]].map(([id,label]) => <button key={id} onClick={() => setActive(id)} className="min-h-10 min-w-max rounded-md border bg-white px-3 text-sm font-semibold">{label}</button>)}</div></div></Card>; }
function Dashboard({ check }: { check: CheckResult | null }) { return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Aktuálne výzvy", grants.filter(g=>g.daysLeft>=30).length, "bez blízkej uzávierky"],["Uzávierka čoskoro", grants.filter(g=>g.daysLeft>=0&&g.daysLeft<30).length, "do 30 dní"],["Ukončené výzvy", grants.filter(g=>g.daysLeft<0).length, "po termíne"],["Zmenené výzvy", grants.filter(g=>g.status==="Zmenená").length, "AI zmena"]].map(([a,b,c]) => <Card key={String(a)} className="p-4 sm:p-5"><p className="text-sm text-slate-500">{a}</p><p className="my-2 text-3xl font-bold sm:text-4xl">{b}</p><Badge tone="blue">{c}</Badge></Card>)}</div>{check && <Card className="border-[#b8d8c8] p-4 sm:p-5"><h3>Výsledok manuálnej kontroly</h3><p className="text-slate-500">Spustené: {check.stamp}</p><div className="grid gap-3 md:grid-cols-3"><Info k="Skontrolované zdroje" v={String(check.checked)} /><Info k="Nájdené zmeny" v={String(check.changes)} /><Info k="Nové dokumenty" v={String(check.docs)} /></div></Card>}</div>; }
function Sources() { return <div className="space-y-5"><Card className="p-4 sm:p-5"><h3>Discovery monitoring nových výziev</h3><p className="text-slate-600">Aplikácia neustále monitoruje hlavné portály, nové podstránky a PDF dokumenty.</p></Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{sources.map(([name, org, url, category, interval, type]) => <Card key={url} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="m-0 text-base">{name}</h3><p className="break-words text-xs text-slate-500">{url}</p></div><Badge>Aktívny</Badge></div><div className="mt-3 grid gap-2 text-sm"><Info k="Organizácia" v={org} /><Info k="Kategória" v={category} /><Info k="Interval" v={interval} /><Info k="Typ" v={type} /></div></Card>)}</div></div>; }
function Grants({ grantId, setGrantId, setActive }: { grantId: string; setGrantId: (id: string) => void; setActive: (id: string) => void }) { return <div className="space-y-4"><Card className="p-4 sm:p-5"><h3>Aktuálnosť výziev</h3><div className="grid gap-3 md:grid-cols-3"><Info k="Aktuálne" v={String(grants.filter(g=>g.daysLeft>=30).length)} /><Info k="Uzávierka čoskoro" v={String(grants.filter(g=>g.daysLeft>=0&&g.daysLeft<30).length)} /><Info k="Ukončené" v={String(grants.filter(g=>g.daysLeft<0).length)} /></div></Card>{grants.map((grant) => <Card key={grant.id} className={`p-4 sm:p-5 ${grant.id === grantId ? "border-[#2f7a58] shadow-lg" : ""}`}><div className="grid gap-3 sm:flex sm:justify-between"><div><h3>{grant.title}</h3><p className="text-sm text-slate-500">{grant.id} · {grant.issuer} · {grant.program}</p></div><div className="flex gap-2 sm:grid sm:justify-items-end"><Badge tone={grantTone(grant)}>{grant.currentState}</Badge><Badge tone={grant.status === "Zmenená" ? "amber" : "blue"}>{grant.status}</Badge></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Info k="Uzávierka" v={grant.deadline} /><Info k="Do uzávierky" v={grant.daysLeft < 0 ? "po termíne" : `${grant.daysLeft} dní`} /><Info k="Alokácia" v={grant.allocation} /><Info k="Pre koho" v={grant.eligibleApplicants} /><Info k="Výška podpory" v={grant.support} /><Info k="Spoluúčasť" v={grant.cofinancing} /></div><div className="mt-4 grid gap-2 sm:flex"><button onClick={() => setGrantId(grant.id)} className="min-h-11 rounded-md bg-[#2f7a58] px-3 text-white">Aktívna výzva</button><button onClick={() => { setGrantId(grant.id); setActive("history"); }} className="min-h-11 rounded-md border px-3">História</button></div></Card>)}</div>; }
function Info({ k, v }: { k: string; v: string }) { return <div className="rounded-md border bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{k}</p><b>{v}</b></div>; }
function HistoryPanel({ grant, check }: { grant: Grant; check: CheckResult | null }) { return <Card className="p-4 sm:p-5"><h3>História zmien</h3><p className="text-slate-500">Zmeny pre {grant.id}: {grant.title}</p><Info k="Dátum uzávierky" v={grant.deadline} /><Info k="Pôvodný zdroj" v={grant.source} />{check && <Info k="Posledná kontrola" v={`${check.stamp}, ${check.changes} zmeny`} />}</Card>; }
function AiPanel({ grant }: { grant: Grant }) { return <Card className="p-4 sm:p-5"><h3>AI analýza</h3><pre className="overflow-auto rounded-lg bg-[#10213a] p-4 text-sm text-white">{JSON.stringify({ grantNumber: grant.id, status: grant.currentState, deadlineAt: grant.deadline, eligibleApplicants: grant.eligibleApplicants, cofinancing: grant.cofinancing, source: grant.source }, null, 2)}</pre></Card>; }
function Clients({ session }: { session: Session }) { return <Card className="p-4 sm:p-5"><h3>Klienti</h3><p className="text-slate-600">{session.role === "Klient" ? `${session.name}: demo profil čaká na doplnenie údajov po plnej aktivácii.` : "Firemné profily, de minimis, SK NACE a záujmové oblasti."}</p></Card>; }
function Matching({ grant }: { grant: Grant }) { return <Card className="p-4 sm:p-5"><div className="flex justify-between gap-3"><div><h3>{grant.matchClient}</h3><p className="text-slate-500">{grant.title}</p></div><div className="grid h-14 w-14 shrink-0 place-items-center rounded-lg bg-green-50 text-lg font-bold text-green-800 sm:h-16 sm:w-16 sm:text-xl">{grant.match}%</div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Info k="Pre koho je výzva" v={grant.eligibleApplicants} /><Info k="Spoluúčasť klienta" v={grant.cofinancing} /></div><p className="mt-4">Výsledok musí manuálne potvrdiť pracovník.</p></Card>; }
function Notifications({ grant }: { grant: Grant }) { return <div className="grid gap-4 md:grid-cols-3">{["Okamžité upozornenia", "Denný súhrn", "Týždenný súhrn"].map((item) => <Card key={item} className="p-4 sm:p-5"><h3>{item}</h3><p className="text-slate-600">Filter: {grant.id}</p><Badge tone="blue">Naplánované</Badge></Card>)}</div>; }
function Admin() { return <div className="grid gap-4 md:grid-cols-3"><Card className="p-4 sm:p-5"><h3>Správa používateľov</h3><p>Pozvánky, schvaľovanie klientov, RBAC a reset hesla.</p></Card><Card className="p-4 sm:p-5"><h3>Nastavenie AI</h3><p>Modely, limity, prompt šablóny.</p></Card><Card className="p-4 sm:p-5"><h3>Log kontrol a chýb</h3><p>Audit log, worker logy a monitoring.</p></Card></div>; }
